### ISSUE TITLE
Error Validation error: {"error_code":500,"message":"org.apache.kafka.connect.errors.ConnectException: Failed to find any class that implements Connector and which..

### ISSUE THREAD

**Issue by Stefen-Taime** [jaumpedro214/posts#6]
this command return error:

CREATE SOURCE CONNECTOR accidents_bronze_source_connector WITH (
    'connector.class' = 'io.debezium.connector.mongodb.MongoDbConnector',
    'mongodb.hosts' = 'mongo:27017',
    'mongodb.name' = 'replica-set',
    'mongodb.authsource' = 'admin',
    'mongodb.user' = 'mongo',
    'mongodb.password' = 'mongo',
    'collection.whitelist' = 'accidents.accidents_bronze',

    'transforms' = 'unwrap',
    'transforms.unwrap.type' = 'io.debezium.connector.mongodb.transforms.ExtractNewDocumentState',
    'transforms.unwrap.drop.tombstones' = 'false',
    'transforms.unwrap.delete.handling.mode' = 'drop',
    'transforms.unwrap.operation.header' = 'true',
    
    'errors.tolerance' = 'all'
);

error: 

Validation error: {"error_code":500,"message":"org.apache.kafka.connect.errors.ConnectException: Failed to find any class that implements Connector and which name matches io.debezium.connector.mongodb.MongoDbConnector, available connectors are: PluginDesc{klass=class org.apache.kafka.connect.tools.MockSinkConnector, name='org.apache.kafka.connect.tools.MockSinkConnector', version='7.3.0-cc-docker-ksql.111-33-ccs', encodedVersion=7.3.0-cc-docker-ksql.111-33-ccs, type=sink, typeName='sink', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.MockSourceConnector, name='org.apache.kafka.connect.tools.MockSourceConnector', version='7.3.0-cc-docker-ksql.111-33-ccs', encodedVersion=7.3.0-cc-docker-ksql.111-33-ccs, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.SchemaSourceConnector, name='org.apache.kafka.connect.tools.SchemaSourceConnector', version='7.3.0-cc-docker-ksql.111-33-ccs', encodedVersion=7.3.0-cc-docker-ksql.111-33-ccs, type=source, typeName='source', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.VerifiableSinkConnector, name='org.apache.kafka.connect.tools.VerifiableSinkConnector', version='7.3.0-cc-docker-ksql.111-33-ccs', encodedVersion=7.3.0-cc-docker-ksql.111-33-ccs, type=sink, typeName='sink', location='classpath'}, PluginDesc{klass=class org.apache.kafka.connect.tools.VerifiableSourceConnector, name='org.apache.kafka.connect.tools.VerifiableSourceConnector', version='7.3.0-cc-docker-ksql.111-33-ccs', encodedVersion=7.3.0-cc-docker-ksql.111-33-ccs, type=source, typeName='source', location='classpath'}"}

**Comment by jaumpedro214** [comment]
Hi, thanks for sharing this issue.

I think that this problem is due to incorrect configuration of the connectors.
Make sure that the connectors are correctly extracted into the folder /plugins, see the image below:

![image](https://user-images.githubusercontent.com/44421368/193858604-8135ffae-0348-494c-ab50-5b0c798910fb.png)

You can download the connectors using the following links:
https://www.confluent.io/hub/debezium/debezium-connector-mongodb
https://www.confluent.io/hub/mongodb/kafka-connect-mongodb

**Comment by Stefen-Taime** [comment]
it good :)

**Comment by Stefen-Taime** [comment]
but 

CREATE STREAM accidents_bronze_stream
(
     _ID                      VARCHAR(STRING)
    ,ID                       VARCHAR(STRING)          
    ,PESID                    VARCHAR(STRING) 
    ,DATA_INVERSA             VARCHAR(STRING) 
    ,DIA_SEMANA               VARCHAR(STRING) 
    ,HORARIO                  VARCHAR(STRING) 
    ,UF                       VARCHAR(STRING) 
    ,BR                       VARCHAR(STRING) 
    ,KM                       VARCHAR(STRING) 
    ,MUNICIPIO                VARCHAR(STRING) 
    ,CAUSA_PRINCIPAL          VARCHAR(STRING) 
    ,CAUSA_ACIDENTE           VARCHAR(STRING) 
    ,ORDEM_TIPO_ACIDENTE      VARCHAR(STRING) 
    ,TIPO_ACIDENTE            VARCHAR(STRING) 
    ,CLASSIFICACAO_ACIDENTE   VARCHAR(STRING) 
    ,FASE_DIA                 VARCHAR(STRING) 
    ,SENTIDO_VIA              VARCHAR(STRING) 
    ,CONDICAO_METEREOLOGICA   VARCHAR(STRING) 
    ,TIPO_PISTA               VARCHAR(STRING) 
    ,TRACADO_VIA              VARCHAR(STRING) 
    ,USO_SOLO                 VARCHAR(STRING) 
    ,ID_VEICULO               VARCHAR(STRING) 
    ,TIPO_VEICULO             VARCHAR(STRING) 
    ,MARCA                    VARCHAR(STRING) 
    ,ANO_FABRICACAO_VEICULO   VARCHAR(STRING) 
    ,TIPO_ENVOLVIDO           VARCHAR(STRING) 
    ,ESTADO_FISICO            VARCHAR(STRING) 
    ,IDADE                    VARCHAR(STRING) 
    ,SEXO                     VARCHAR(STRING) 
    ,ILESOS                   INTEGER         
    ,FERIDOS_LEVES            INTEGER         
    ,FERIDOS_GRAVES           INTEGER         
    ,MORTOS                   INTEGER         
    ,LATITUDE                 VARCHAR(STRING) 
    ,LONGITUDE                VARCHAR(STRING) 
    ,REGIONAL                 VARCHAR(STRING) 
    ,DELEGACIA                VARCHAR(STRING) 
    ,UOP                      VARCHAR(STRING) 
)
WITH (
    kafka_topic = 'replica-set.accidents.accidents_bronze',
    value_format = 'avro'
);


Error:
Could not get latest schema for subject replica-set.accidents.accidents_bronze-value
Caused by: schema-registry

**Comment by Stefen-Taime** [comment]
I don't have the accident database in mongo
